#Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Encoding
encoding:         'utf-8'

# Setup
title:            Spark AT SJTU
tagline:          Spark AT SJTU
paginate:         8
baseurl:          /

pages_list:
  Home:  '/'
  People: '/iiot/people'
  Projects:   '/iiot/projects'
  Data:   '/iiot/data'
  Contact:  '/iiot/contact'

excerpt_separator:  <!--more-->
