#Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Encoding
encoding:         'utf-8'

# Setup
title:            Spark AT SJTU
tagline:          Spark AT SJTU
paginate:         8
baseurl:          /iiot-spark/

pages_list:
  Home:  '/iiot-spark/'
  People: '/iiot-spark/people'
  Projects:   '/iiot-spark/projects'
  Data:   '/iiot-spark/data'
  Contact:  '/iiot-spark/contact'

excerpt_separator:  <!--more-->
